name: Check Patch Duplicates
on:
  pull_request:
    branches: [ master, Development ]

# Restrict the permissions of the ephemeral GitHub token used by this workflow
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check C# code style
      run: |
        python3 DupeFinder.py -c
