name: Build-PR
on:
  workflow_dispatch:
    inputs:
      PR:
        description: PR Number
        required: true
  pull_request_target:
    branches: [ master, Development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Prebuild
      run: |
        python3 --version
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull --no-ff --no-commit --allow-unrelated-histories -X theirs origin pull/${{ github.event.pull_request.number }}${{ github.event.inputs.PR }}/head:
        git status
        wget https://raw.githubusercontent.com/CombatExtended-Continued/CombatExtended/Development/Make.py -O Make.py
        mkdir -p Assemblies
        mkdir -p AssembliesCore
        mkdir -p AssembliesCompat
        mkdir -p ${{ runner.temp }}/downloads
        rm -rf AssemblyPublicizer
        git clone https://github.com/CombatExtended-Continued/AssemblyPublicizer
        
    - name: build loader
      run: |
        TEMP=${{ runner.temp }}/ python Make.py --csproj Source/Loader/Loader.csproj --output Assemblies/0CombatExtendedLoader.dll --download-libs --all-libs
        
    - name: build core
      run: |
        TEMP=${{ runner.temp }}/ python Make.py --csproj Source/CombatExtended/CombatExtended.csproj --output Assemblies/CombatExtended.dll --download-libs --all-libs --publicizer $PWD/AssemblyPublicizer

    - name: build compat
      run: |
        TEMP=${{ runner.temp }}/ for f in {MultiplayerCompat,MiscTurretsCompat,BetterTurretsCompat}; do python Make.py --csproj Source/$f/$f.csproj --output AssembliesCompat/$f.dll --download-libs --all-libs --publicizer $PWD/AssemblyPublicizer -- -r:Assemblies/CombatExtended.dll; done
        
    - name: package
      run: |
        mkdir CombatExtended
        cp -r Source/ Assemblies/ AssembliesCompat/ AssembliesCore/ About/ Defs/ Languages/ Patches/ Royalty/ Ideology/ Sounds/ Textures/ LoadFolders.xml README.md SupportedThirdPartyMods.md CombatExtended
        zip -9 -r build.zip CombatExtended
    - name: Upload to DO
      run: |
        printf "%s" "$SSH_KEY" > id_ecdsa
        echo "$SSH_KEY_PUB" > id_ecdsa.pub
        chmod 600 id_ecdsa
        echo put build.zip CombatExtended-${{ github.run_id }}.zip | sftp -oStrictHostKeyChecking=no -P 2022 -i ./id_ecdsa combatextended@combatextended.lp-programming.com
      
      shell: bash
      env:
        SSH_KEY: ${{secrets.ID_ECDSA}}
        SSH_KEY_PUB: ${{secrets.ID_ECDSA_PUB}}

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}${{ github.event.inputs.PR }}
        body: |
          You can download the rebuilt assembly for this PR here: https://combatextended.lp-programming.com/CombatExtended-${{ github.run_id }}.zip
    - name: Add Label
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: "Download in Comments"
        number: ${{ github.event.pull_request.number }}${{ github.event.inputs.PR }}
          
